export interface MarcValueDefinition {
  fullCode: string; // napr. "008.35-37"
  inputType: 'static-dropdown' | 'autocompleter';
  translationPrefix: string; // napr. "marcData.008.35-37."
  options: string[];
  showCodesRight?: boolean;
}

export const MARC_VALUE_DEFINITIONS: MarcValueDefinition[] = [
  {
    fullCode: '008.15-17',
    inputType: 'static-dropdown',
    translationPrefix: 'marcData.008.15-17.',
    options: [
      'aa ',
      'ae ',
      'ag ',
      'ai ',
      'aj ',
      'ao ',
      'at ',
      'au ',
      'be ',
      'bl ',
      'bn ',
      'bo ',
      'bu ',
      'bw ',
      'cau',
      'cc ',
      'ch ',
      'ci ',
      'ck ',
      'cl ',
      'cr ',
      'cu ',
      'cy ',
      'dk ',
      'dr ',
      'ec ',
      'enk',
      'er ',
      'es ',
      'et ',
      'fi ',
      'fr ',
      'gr ',
      'gs ',
      'gw ',
      'ho ',
      'hu ',
      'ic ',
      'ie ',
      'ii ',
      'io ',
      'ir ',
      'is ',
      'it ',
      'ja ',
      'jo ',
      'kg ',
      'kn ',
      'ko ',
      'kv ',
      'le ',
      'li ',
      'lv ',
      'mg ',
      'mnu',
      'mo ',
      'mp ',
      'mv ',
      'mx ',
      'my ',
      'ncu',
      'ne ',
      'no ',
      'nz ',
      'pe ',
      'ph ',
      'pl ',
      'pn ',
      'po ',
      'py ',
      'rb ',
      'rm ',
      'ru ',
      'sa ',
      'sp ',
      'stk',
      'sw ',
      'sy ',
      'sz ',
      'th ',
      'tu ',
      'ua ',
      'un ',
      'utu',
      'uy ',
      'uz ',
      've ',
      'vm ',
      'vp ',
      'wlk',
      'xk ',
      'xn ',
      'xo ',
      'xr ',
      'xra',
      'xv ',
      'xx ',
      'xxc',
      'xxk',
      'xxu',
    ],
    showCodesRight: true,
  },
  {
    fullCode: '008.35-37',
    inputType: 'static-dropdown',
    translationPrefix: 'marcData.008.35-37.',
    options: [
      'alb',
      'alt',
      'amh',
      'ara',
      'aze',
      'baq',
      'bel',
      'bos',
      'bre',
      'bul',
      'cat',
      'chi',
      'chm',
      'chu',
      'cze',
      'dan',
      'dut',
      'eng',
      'epo',
      'est',
      'fin',
      'fiu',
      'fre',
      'fry',
      'geo',
      'ger',
      'gre',
      'heb',
      'hrv',
      'hun',
      'ice',
      'ind',
      'ita',
      'jpn',
      'kor',
      'lat',
      'lav',
      'lit',
      'mac',
      'map',
      'may',
      'mon',
      'mul',
      'nds',
      'per',
      'phi',
      'pol',
      'por',
      'rum',
      'rus',
      'sah',
      'scr',
      'sla',
      'slo',
      'slv',
      'spa',
      'srd',
      'srp',
      'swe',
      'tur',
      'ukr',
      'und',
      'uzb',
      'vie',
      'wen',
      'yid',
      'zxx',
    ],
    showCodesRight: true,
  },
  {
    fullCode: '008.6',
    inputType: 'static-dropdown',
    translationPrefix: 'marcData.008.6.',
    options: ['c', 'd', 'e', 'm', 'n', 'p', 'q', 'r', 's', 't', 'u', '|'],
    showCodesRight: true,
  },
];
